### PR TITLE
[FEATURE] Prefer local over global CLI version

### PR DESCRIPTION
**Pull request by matz3**
When running the global "ui5" command while a local @ui5/cli version is
installed for the current project, the local one should be preferred.

Fixes: #58

### CODE REVIEW

**Comment by RandomByte** [comment]
*rebased*

**Comment by RandomByte** [comment]
Is "Prefer local over global CLI version" really a fix or rather a feature? I would opt for the latter

**Comment by matz3** [comment]
Yes, I think feature is a better fit.

**Comment by matz3** [comment]
@RandomByte good idea. This also helps to see whether a locally linked ui5-cli project is used.
I also like the README explanation 👍

But the ENV var is strange. I would expect to have a general "UI5 CLI" prefix that could be used in future for more variables, like `UI5CLI_*` or `UI5_CLI_*`.
And a shorter one... what about `UI5_CLI_NO_LOCAL=true`?
This would also fit the a command option that can be used in "XO" for the same matter, which is something to think about:
https://github.com/xojs/xo/blob/d1fd3e127b191b701716d6f775b6f5c8c5db3778/cli.js#L10

About the `console.info` logs. I think we shouldn't always log this. Especially not in such a verbose way. [XO](https://github.com/xojs/xo/blob/d1fd3e127b191b701716d6f775b6f5c8c5db3778/cli.js#L12) and [AVA](https://github.com/avajs/ava/blob/6ab6d35d9b8c4652a672b804016aa22c9e4f5983/cli.js#L8) just use the [debug](https://www.npmjs.com/package/debug) module. I would only expect them with `--verbose` or `DEBUG=*`.

**Comment by RandomByte** [comment]
Done

**Comment by RandomByte** [comment]
**Note** (just came to my mind): When using a CLI release containing this change in a repository that uses a release without it, no `INFO: Using local @ui5/cli installation` information will be logged due to the missing setTimeout in older `bin/ui5.js` versions.

**Comment by matz3** [comment]
Yes, that's correct, but I think this can be neglected.

**Pull request merged**
